name: plant_monitor
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.4.1
  firebase_database: ^10.0.9
  percent_indicator: ^4.2.2
  http: ^0.13.5
  firebase_messaging: ^14.2.1
  flutter_local_notifications: ^13.0.0
  syncfusion_flutter_charts: ^20.4.50
  app_settings: ^4.2.0
  environment_sensors: ^0.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
