// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUS7BPyBvhVRGB8gUsHYMOGkxqChLQZyQ',
    appId: '1:241290221299:web:6ebe151b54d3593debc986',
    messagingSenderId: '241290221299',
    projectId: 'plantmonitor-ec8fe',
    authDomain: 'plantmonitor-ec8fe.firebaseapp.com',
    databaseURL: 'https://plantmonitor-ec8fe-default-rtdb.firebaseio.com',
    storageBucket: 'plantmonitor-ec8fe.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBALd0iUW8eYA5eGcGz3eUGQQsnjTah0SE',
    appId: '1:241290221299:android:373df407d47591e1ebc986',
    messagingSenderId: '241290221299',
    projectId: 'plantmonitor-ec8fe',
    databaseURL: 'https://plantmonitor-ec8fe-default-rtdb.firebaseio.com',
    storageBucket: 'plantmonitor-ec8fe.appspot.com',
  );
}
